board: Fluid NC 6x CNC Controller
name: FoxAlien Vasto
stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 4
  disable_delay_us: 0
  segments: 6

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 320.000
    # It will do 7600 on its own
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 425.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.21
        direction_pin: I2SO.20:low
        disable_pin: I2SO.23

  y:
    steps_per_mm: 320.000
    # It will do 5600 on its own
    max_rate_mm_per_min: 4500.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 470.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.39:low
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.18
        direction_pin: I2SO.17:low
        # direction_pin: I2SO.17
        disable_pin: I2SO.16

    motor1:
      limit_neg_pin: gpio.34:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.13
        direction_pin: I2SO.12
        disable_pin: I2SO.15

  z:
    steps_per_mm: 800.000
    # It will do 2600 on its own
    max_rate_mm_per_min: 2000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 114.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 114.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.9
        disable_pin: I2SO.8

#  a:
#    steps_per_mm: 53.400
#    max_rate_mm_per_min: 5000.000
#    acceleration_mm_per_sec2: 100.000
#    max_travel_mm: 960.000
#    soft_limits: false
#    homing:
#      cycle: 2
#      positive_direction: false
#      mpos_mm: 0.000
#      feed_mm_per_min: 100.000
#      seek_mm_per_min: 200.000
#      settle_ms: 500
#      seek_scaler: 1.100
#      feed_scaler: 1.100
#
#    motor0:
#      limit_neg_pin: gpio.32:low
#      limit_pos_pin: NO_PIN
#      limit_all_pin: NO_PIN
#      hard_limits: false
#      pulloff_mm: 3.000
#      standard_stepper:
#        step_pin: I2SO.5
#        direction_pin: I2SO.4
#        disable_pin: I2SO.7

# B axis used for RapidChange dust cover stepper driver
  b:
    steps_per_mm: 50.000
    max_rate_mm_per_min: 2500.000
    acceleration_mm_per_sec2: 300.000
    max_travel_mm: 35.000
    soft_limits: false
    #homing:
    #  cycle: 2
    #  positive_direction: false
    #  mpos_mm: 0.000
    #  feed_mm_per_min: 100.000
    #  seek_mm_per_min: 800.000
    #  settle_ms: 500
    #  seek_scaler: 1.100
    #  feed_scaler: 1.100
 
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000
      standard_stepper:
        step_pin: I2SO.2
        direction_pin: I2SO.1
        disable_pin: I2SO.0


i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
  #frequency_hz: 8000000

# Pins 2 and 26 do not have hardware pullup resistors, so do it in the ESP32
probe:
  pin: gpio.26:low:pu
  toolsetter_pin: NO_PIN
  check_mode_start: true

# Pins 2 and 26 do not have hardware pullup resistors, so do it in the ESP32
control:
  safety_door_pin: gpio.2:low:pu

# Using MOSFETs (Check Spindle Pin Usage)
coolant:
  flood_pin: gpio.12
  mist_pin: gpio.4
  #delay_ms: 1000

start:
  must_home: true
  check_limits: true

# H100 Spindle Config (new style UART config)
uart1:
  txd_pin: gpio.15
  rxd_pin: gpio.16
  rts_pin: gpio.14
  baud: 19200
  mode: 8N1
H100:
  uart_num: 1
  modbus_id: 1
  tool_num: 0
  speed_map: 0=0% 6000=25% 24000=100%
  off_on_alarm: true
  atc:
  m6_macro: $LocalFS/Run=tc.nc

# H100 Spindle Config (old style UART config)
#H100:
#  uart:
#    txd_pin: gpio.15
#    rxd_pin: gpio.16
#    rts_pin: gpio.14
#    baud: 19200
#    mode: 8N1
#  modbus_id: 1
#  tool_num: 0
#  speed_map: 0=0% 6000=25% 24000=100%
#  off_on_alarm: true

# FluidNC Pendant (Only works with new style UART config)
uart2:
  txd_pin: gpio.25
  rxd_pin: gpio.27
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1
uart_channel2:
  report_interval_ms: 75
  uart_num: 2

# Pin for tool setter
user_inputs:
  digital0_pin: gpio.33

macros:
  after_homing: $LocalFS/Run=init.nc

# Spindle spins 100RPM low at slow speeds
#RapidChange:
#  alignment: X_AXIS
#  direction: POSITIVE
#  number_of_pockets: 6
#  pocket_offset: 45.000
#  x_pocket_1: 100.300
#  y_pocket_1: 469.000
#  z_engage: 19.000
#  z_traverse: 62.000
#  z_safe_clearance: 114.000
#  engage_feed_rate: 2350
#  load_rpm: 1750
#  unload_rpm: 1900
#  dust_cover_enabled: True
#  tool_recognition_enabled: True
#  tool_setter_enabled: True
#  x_tool_setter: 160.950
#  y_tool_setter: 409.100
#  z_seek_start: 114.000
#  z_safe_tool_setter: 114.000
#  set_tool_offset: 50.000
#  seek_feed_rate: 500
#  seek_retreat: 5
#  set_feed_rate: 100
#  set_tool_max_travel: 55.000
#  dust_cover_axis: B_AXIS
#  dust_cover_open_position: 35.000
#  dust_cover_closed_position: 0.000
#  dust_cover_use_output: False
#  z_tool_recognition_zone_1: 51.000
#  z_tool_recognition_zone_2: 55.000
#  dust_cover_pin: NO_PIN
#  tool_recognition_pin: gpio.33
